// CATEGORY_INSTANCE (name, categoryName)

CATEGORY_INSTANCE(Synth, Synth)
CATEGORY_INSTANCE(Oscillator1, Oscillator)
CATEGORY_INSTANCE(Oscillator2, Oscillator)
CATEGORY_INSTANCE(Envelope1, Envelope)
CATEGORY_INSTANCE(Envelope2, Envelope)
CATEGORY_INSTANCE(Lfo, Lfo)
CATEGORY_INSTANCE(Filter, Filter)
CATEGORY_INSTANCE(Delay, Delay)